### ISSUE TITLE
Cannot pip install cartopy

### ISSUE THREAD

**Issue by adria360** [grst/geos#17]
Attempting to install Cartopy-0.17.0 after pip installing geos.  Receive the following error:

UserWarning: Unable to determine GEOS version. Ensure you have 3.3.3 or later installed, or installation may fail.

Is there a version 3.3.3 available for pip install? Can you provide assistance in getting the installation completed?

**Comment by grst** [comment]
I suspect cartopy expects a different "geos" package than this one. 
There is certainly no 3.* version of this package.
