### ISSUE TITLE
Add markdown table support for Read the Docs

### ISSUE THREAD

**Issue by zstadler** [grst/geos#33]
By default, Read the Doc's Sphinx engine does not support Markdown tables.

As a result, [here](https://geos.readthedocs.io/en/latest/users.html#running-geos-in-a-docker-container) we see

![image](https://user-images.githubusercontent.com/1304610/120065459-11140580-c07a-11eb-8c06-222d0335800d.png)

rather than

![image](https://user-images.githubusercontent.com/1304610/120065484-330d8800-c07a-11eb-9050-d422c4757b28.png)

[github.com/ryanfox/sphinx-markdown-tables](https://github.com/ryanfox/sphinx-markdown-tables#readme) provides an extension that adds the required support. According to its docs, [the solution](https://github.com/ryanfox/sphinx-markdown-tables#quick-version) is to add `sphinx_markdown_tables` to `extensions` in `conf.py`, like so:

    extensions = [
        'sphinx_markdown_tables',
    ]

_Note:_
According to [this issue](https://github.com/ryanfox/sphinx-markdown-tables/issues/9), you may also need to add `sphinx_markdown_tables` to ReadtheDocs' `requirements.txt` file.

**Comment by grst** [comment]
Hi @zstadler, 

thanks for the hint, that looks great! 
I currently don't have a lot of time to maintain this package -- do you want to put a PR together? 

Cheers, 
Gregor
